{% set name = "slack-bolt" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_bolt-{{ version }}.tar.gz
  sha256: 43b121acf78440303ce5129e53be36bdfe5d926a193daef7daf2860688e65dd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner ==5.2
    - pip
  run:
    - python >=3.6
    - slack-sdk <4,>=3.21.2

test:
  imports:
    - slack_bolt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackapi/bolt-python
  summary: The Bolt Framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbiette
